### ISSUE TITLE
[meta] Polish the template code and resources

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#104]
Improve the quality of the visuals and code. Design a clear API to allow for further customization and document it.

- [x] Conditionally inject the WebVR polyfill if needed (#126)
- [x] Organise in a class hierarchy the code in the `WebVRCamera` script.
- [x] Define a clear API for communicating between the scripts and JS code (related to #136)
- [x] Split the template into several folders and organize the assets properly.
- [x] Leave the code in the WebVR plugin as a communication interface.
- [x] Polish CSS code

**Comment by cvan** [comment]
as a rough start: https://github.com/mozilla/unity-webvr-export/issues/126#issue-296063536

**Comment by caseyyee** [comment]
All the Camera, controller and JS code has been refactored since and should address all these issues.

These PR's are the major starting points:
https://github.com/mozilla/unity-webvr-export/pull/328
https://github.com/mozilla/unity-webvr-export/pull/215
