### ISSUE TITLE
[meta] APIs

### ISSUE THREAD

**Issue by delapuente** [mozilla/unity-webvr-export#136]
Ease the customization of the template by providing the proper documentation and APIs.

- [x] Declare a clear interface to enter/exit VR mode.
- [x] Provide a promise-based _façade_ API to send and receive messages to and from Unity.
- [x] Provide an easy way to customize the loading screen.
- [x] Provide a webby procedure to customize the template. 
- [x] Do not hardcode values in JavaScript.
- [x] Configuration must happen in Unity and be sent to JavaScript.

**Comment by caseyyee** [comment]
* Provide a promise-based façade API to send and receive messages to and from Unity.

We use the Unity sendMessage (see https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html), seems to be suitable for most cases. It's the standard way to message in Unity, so I don't think there is anything necessary beyond this.

* Provide an easy way to customize the loading screen.

It's pretty clear how to customize the template:
https://docs.unity3d.com/Manual/webgl-templates.html

We've changed some aesthetics, but functionally its the same.  Of course, we have some additional changes in the form of webvr.js that helps mediate WebVR API usage.  Will create a separate issue to document.

* Provide a webby procedure to customize the template.

Pretty vague, but I'll consider it the same as the above question. I think we could provide more in-Unity options though.  Again, filed as a separate issue.
