### ISSUE TITLE
[meta] Telemetry: Usage Statistics, Errors, Feedback

### ISSUE THREAD

**Issue by cvan** [mozilla/unity-webvr-export#165]
This is a parent (meta) bug for tasks around built-in telemetry mechanisms for projects that have integrated the [WebVR Assets](https://assetstore.unity.com/packages/templates/systems/webvr-assets-109152) Unity package in their games (not only for the [Demo scene](https://mozilla.github.io/unity-webvr-export/Build/)).

- [x] collect JavaScript errors (call stacks and anonymous browser/platform information) anonymously (no [PII](https://en.wikipedia.org/wiki/Personally_identifiable_information)) using [Sentry](https://sentry.io/) so we (_Unity WebVR Assets_ project maintainers) can track errors from usage in the wild (localhost, ngrok, localtunnel, non-HTTPS traffic excluded) (see **issue #166**)
- [x] create a new JavaScript template file `telemetry.js` for telemetry services (see **issue #172**)
- [x] collect generic usage information (i.e., basic Google Analytics for determining approximate MAU and DAU) (see **issue #169**)
- [x] collect basic performance timings (e.g., navigation, canvas, WebGL, Unity Engine emscripten module) (see **issue #170**)
- [x] <s>create a `Help` modal screen (see **issue #167**)</s>
- [x] document telemetry services, data-collection practices (see **issue #164**)
- [x] submit a [Request for Data Collection Review](https://github.com/mozilla/data-review/blob/master/request.md) for the folks on the Mozilla Data Metrics team (see **issue #168**)

**Comment by delapuente** [comment]
We agreed on not including the meta-bug in the milestone. Removing.

**Comment by cvan** [comment]
this has been completed. thanks a ton, @delapuente!
