### ISSUE TITLE
[meta] Input System

### ISSUE THREAD

**Issue by caseyyee** [mozilla/unity-webvr-export#8]
Connect the Gamepad API and other input systems (mouse, keyboard) to the Unity Input system so whatever thing working on Unity, must work on the web without adaptations.

**Comment by caseyyee** [comment]
I use `Input.GetKey ("joystick button 1")`

Will probably need to figure out some way of mapping friendlier name to axis' and buttons for each controller type, or provide some sort of component to help the handling of it.

**Comment by delapuente** [comment]
I'm tracking the documentation effort in #25.

**Comment by delapuente** [comment]
Related to #124. We should provide those mappings to make JS work like Unity (not the other way around).

**Comment by delapuente** [comment]
These are the things that this issue should track:

- [ ] Axis directions should be those provided by Unity.
- [ ] Name of the controller buttons should be those used by Unity.
- [ ] Name of the keyboard keys should be those used by Unity.
- [ ] Mimic Unity behaviour when dealing with VR controllers in design-time.
- [ ] Provide _force-feedback/vibration_ through [`GamePadHaptic` extension](https://w3c.github.io/gamepad/extensions.html#gamepadhapticactuator-interface) to the GamePad API.

**Comment by caseyyee** [comment]
Fixed with https://github.com/mozilla/unity-webvr-export/commit/b0a1307d5f722f066f3a0f5c69ae4c889fee9457
